on:
  workflow_call:
    inputs:
      cache_key:
        type: string
        required: false
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  rainforest:
    runs-on: ubuntu-latest
    name: Run Rainforest
    steps:
      - uses: actions/checkout@v2
      - name: Rainforest
        uses: ./
        with:
          token: ${{ secrets.RAINFOREST_API_TOKEN }}
          run_group_id: 9861
          cache_key: ${{ inputs.cache_key }}
